// Auto-derived from Kingdom_of_Claudes_Beloved_MDs/UI_BUTTONS_AND_COMMANDS.md
// Structured, searchable, bilingual source for the in-app Help panel.

export type HelpLang = 'en' | 'he';

export interface HelpEntry {
  id: string;        // unique kebab-case id, e.g. 'cmd-start-session' or 'statusbar-history'
  section: string;   // must equal one HelpSection.key
  name: string;      // the button/command label as shown in the UI (English)
  tooltip?: string;  // the short English hover tooltip if the doc lists one
  detailEn: string;  // detailed English explanation
  detailHe: string;  // detailed Hebrew explanation
}

export interface HelpSection {
  key: string;
  titleEn: string;
  titleHe: string;
}

export const HELP_SECTIONS: HelpSection[] = [
  { key: 'commands', titleEn: 'Commands', titleHe: 'פקודות' },
  { key: 'statusbar', titleEn: 'Status Bar', titleHe: 'שורת המצב' },
  { key: 'inputarea', titleEn: 'Input Area', titleHe: 'אזור הקלט' },
  { key: 'app', titleEn: 'App Controls', titleHe: 'בקרות כלליות' },
  { key: 'chatview', titleEn: "Chat View", titleHe: "תצוגת הצ'אט" },
  { key: 'panels', titleEn: 'Feature Panels', titleHe: 'פאנלים' },
  { key: 'selectors', titleEn: 'Selectors', titleHe: 'בוררים' },
];

export const HELP_ENTRIES: HelpEntry[] = [
  // ===== Part 1 — Commands =====
  {
    id: 'commands-start-session',
    section: 'commands',
    name: 'ClaUi: Start New Session',
    tooltip: 'Start a new Claude Code session',
    detailEn: 'Spawns a fresh CLI process in a new ClaUi tab and opens the chat panel, ready for the first prompt.',
    detailHe: "מפעיל תהליך CLI חדש בלשונית ClaUi חדשה ופותח את חלון הצ'אט, מוכן לפקודה הראשונה.",
  },
  {
    id: 'commands-stop-session',
    section: 'commands',
    name: 'ClaUi: Stop Session',
    tooltip: 'Stop the active session',
    detailEn: "Terminates the current session's CLI process tree (via taskkill on Windows) while keeping the transcript visible.",
    detailHe: 'מסיים את עץ תהליכי ה-CLI של הסשן הנוכחי (באמצעות taskkill ב-Windows) תוך שמירה על התמלול הגלוי.',
  },
  {
    id: 'commands-resume-session',
    section: 'commands',
    name: 'ClaUi: Resume Session',
    tooltip: 'Resume a previous session',
    detailEn: 'Reopens a past session by id and respawns the CLI with --resume, restoring the prior conversation context on the correct provider.',
    detailHe: 'פותח מחדש סשן קודם לפי מזהה ומפעיל מחדש את ה-CLI עם --resume, ומשחזר את הקשר השיחה הקודם על הספק הנכון.',
  },
  {
    id: 'commands-discover-sessions',
    section: 'commands',
    name: 'ClaUi: Discover All Sessions',
    tooltip: 'Scan disk for all past sessions',
    detailEn: 'Scans the on-disk session stores (~/.claude/projects/, ~/.codex/sessions/) and lists every resumable conversation found.',
    detailHe: 'סורק את מאגרי הסשנים בדיסק (~/.claude/projects/, ~/.codex/sessions/) ומציג כל שיחה ניתנת לשחזור שנמצאה.',
  },
  {
    id: 'commands-show-history',
    section: 'commands',
    name: 'ClaUi: Conversation History',
    tooltip: 'Browse previous conversations',
    detailEn: 'Opens the conversation-history browser so you can revisit and reopen earlier chats.',
    detailHe: 'פותח את דפדפן היסטוריית השיחות כדי לחזור ולפתוח שיחות קודמות.',
  },
  {
    id: 'commands-compact',
    section: 'commands',
    name: 'ClaUi: Compact Context',
    tooltip: 'Compact the conversation context',
    detailEn: "Triggers the CLI's context-compaction so a long conversation is summarized into a smaller footprint, freeing context-window room.",
    detailHe: 'מפעיל דחיסת-הקשר של ה-CLI כך ששיחה ארוכה מסוכמת לטביעת-רגל קטנה יותר, ומשחרר מקום בחלון ההקשר.',
  },
  {
    id: 'commands-send-message',
    section: 'commands',
    name: 'ClaUi: Send Message',
    tooltip: 'Send a message to the session',
    detailEn: 'Programmatic entry point that sends text to the active session — the same path the Send button uses.',
    detailHe: 'נקודת כניסה תוכניתית ששולחת טקסט לסשן הפעיל — אותו מסלול שבו משתמש כפתור ה-Send.',
  },
  {
    id: 'commands-cancel-request',
    section: 'commands',
    name: 'ClaUi: Cancel Current Response',
    tooltip: 'Cancel the current response',
    detailEn: 'Interrupts the in-flight model turn without ending the session (same as the Cancel/Esc action in the input area).',
    detailHe: 'קוטע את תור-המודל שמתבצע כרגע בלי לסיים את הסשן (זהה לפעולת Cancel/Esc באזור הקלט).',
  },
  {
    id: 'commands-toggle-view',
    section: 'commands',
    name: 'ClaUi: Toggle Chat/Terminal View',
    tooltip: 'Switch between chat and terminal view',
    detailEn: 'Flips the active tab between the rich chat UI and the raw terminal view of the same session.',
    detailHe: "מחליף את הלשונית הפעילה בין ממשק הצ'אט העשיר לבין תצוגת הטרמינל הגולמית של אותו סשן.",
  },
  {
    id: 'commands-send-file-path-to-chat',
    section: 'commands',
    name: 'ClaUi: Send Path to Chat',
    tooltip: 'Send the selected file path to chat',
    detailEn: "Explorer/editor context action that inserts the selected file's path into the chat input — useful for referencing files in a prompt.",
    detailHe: 'פעולת הקשר ב-Explorer/עורך שמכניסה את נתיב הקובץ הנבחר לקלט הצ\'אט — שימושי להפניה לקבצים בפקודה.',
  },
  {
    id: 'commands-open-plan-docs',
    section: 'commands',
    name: 'ClaUi: Open Plan Document',
    tooltip: 'Open plan document in browser',
    detailEn: 'Opens the plan document generated during Plan Mode in your browser for full-page reading.',
    detailHe: 'פותח בדפדפן את מסמך התוכנית שנוצר במצב Plan, לקריאה במסך מלא.',
  },
  {
    id: 'commands-open-log-directory',
    section: 'commands',
    name: 'ClaUi: Open Log Directory',
    tooltip: 'Open the ClaUi log directory',
    detailEn: 'Reveals the extension-managed log folder (ClaUiLogs) in your OS file explorer for troubleshooting.',
    detailHe: 'חושף את תיקיית הלוגים המנוהלת על-ידי התוסף (ClaUiLogs) בסייר הקבצים של מערכת ההפעלה, לצורך תחקור תקלות.',
  },
  {
    id: 'commands-send-feedback',
    section: 'commands',
    name: 'ClaUi: Send Feedback',
    tooltip: 'Send feedback to the ClaUi team',
    detailEn: 'Opens the feedback flow (bug report / feature request / email) that submits via Formspree.',
    detailHe: "פותח את זרימת המשוב (דיווח באג / בקשת פיצ'ר / אימייל) שנשלחת דרך Formspree.",
  },
  {
    id: 'commands-toggle-achievements',
    section: 'commands',
    name: 'ClaUi: Toggle Achievements',
    tooltip: 'Show/hide the Achievements panel',
    detailEn: 'Opens or closes the gamified Achievements panel that tracks usage milestones.',
    detailHe: 'פותח או סוגר את פאנל ההישגים הממוחק (gamified) שעוקב אחרי אבני-דרך בשימוש.',
  },
  {
    id: 'commands-toggle-team-panel',
    section: 'commands',
    name: 'ClaUi: Toggle Agent Teams Panel',
    tooltip: 'Show/hide the Agent Teams panel',
    detailEn: 'Opens the Agent Teams panel showing tasks, messages, and activity across collaborating agents.',
    detailHe: 'פותח את פאנל צוותי הסוכנים המציג משימות, הודעות ופעילות בין סוכנים משתפי-פעולה.',
  },
  {
    id: 'commands-toggle-mcp-panel',
    section: 'commands',
    name: 'ClaUi: MCP Servers',
    tooltip: 'Open the MCP servers panel',
    detailEn: 'Opens the MCP (Model Context Protocol) panel to view, add, and debug configured MCP servers.',
    detailHe: 'פותח את פאנל ה-MCP (Model Context Protocol) לצפייה, הוספה ותחקור של שרתי MCP מוגדרים.',
  },
  {
    id: 'commands-open-worktree-panel',
    section: 'commands',
    name: 'ClaUi: Worktrees Dashboard',
    tooltip: 'Open the Git worktrees dashboard',
    detailEn: 'Opens a dashboard listing every Git worktree and the sessions running on each.',
    detailHe: 'פותח לוח מחוונים המציג כל worktree של Git ואת הסשנים הרצים על כל אחד.',
  },
  {
    id: 'commands-open-workstream-map',
    section: 'commands',
    name: 'ClaUi: Open Workstream Map',
    tooltip: 'Open the Workstream Map',
    detailEn: "Opens the Workstream Map, a visual subway-style map of the current project's sessions and branches.",
    detailHe: 'פותח את ה-Workstream Map — מפה ויזואלית בסגנון רכבת-תחתית של הסשנים והענפים בפרויקט הנוכחי.',
  },
  {
    id: 'commands-open-workstream-portfolio',
    section: 'commands',
    name: 'ClaUi: Open Workstream Portfolio',
    tooltip: 'Open the multi-project Workstream Portfolio',
    detailEn: 'Opens the portfolio view that aggregates Workstream Maps across multiple projects.',
    detailHe: 'פותח את תצוגת התיק (portfolio) שמאחדת מפות Workstream על פני מספר פרויקטים.',
  },
  {
    id: 'commands-smart-search-open',
    section: 'commands',
    name: 'ClaUi: Open Smart Search',
    tooltip: 'Open Smart Search',
    detailEn: 'Opens a Smart Search tab — an AI agent that finds past sessions by meaning, not just keywords.',
    detailHe: 'פותח לשונית Smart Search — סוכן AI שמוצא סשנים קודמים לפי משמעות, לא רק לפי מילות מפתח.',
  },
  {
    id: 'commands-create-worktree-session',
    section: 'commands',
    name: 'ClaUi: New Worktree Session',
    tooltip: 'Start a session in a new Git worktree',
    detailEn: 'Creates a new Git worktree and starts a session inside it, isolating the work from your main checkout.',
    detailHe: 'יוצר worktree חדש של Git ומתחיל בו סשן, ומבודד את העבודה מה-checkout הראשי.',
  },
  {
    id: 'commands-move-session-to-worktree',
    section: 'commands',
    name: 'ClaUi: Move Current Session to Worktree',
    tooltip: 'Move this session into a worktree',
    detailEn: 'Relocates the current session into a (new or existing) worktree so its changes are isolated on a separate branch/folder.',
    detailHe: 'מעביר את הסשן הנוכחי ל-worktree (חדש או קיים) כך שהשינויים שלו מבודדים בענף/תיקייה נפרדים.',
  },
  {
    id: 'commands-authenticate-happy',
    section: 'commands',
    name: 'ClaUi: Authenticate Happy Coder',
    tooltip: 'Authenticate the Happy provider',
    detailEn: 'Runs the auth flow for the Happy (remote) provider so its sessions can connect.',
    detailHe: 'מריץ את זרימת האימות לספק Happy (מרוחק) כדי שהסשנים שלו יוכלו להתחבר.',
  },
  {
    id: 'commands-switch-provider-with-context',
    section: 'commands',
    name: 'ClaUi: Switch Provider (Carry Context)',
    tooltip: 'Switch provider, carrying context over',
    detailEn: 'Hands the current conversation off to a different provider (e.g., Claude ↔ Codex), packaging context so the new provider continues where you left off.',
    detailHe: 'מעביר את השיחה הנוכחית לספק אחר (למשל Claude ↔ Codex), ואורז את ההקשר כך שהספק החדש ממשיך מהמקום שבו הפסקת.',
  },
  {
    id: 'commands-switch-claude-account-with-context',
    section: 'commands',
    name: 'ClaUi: Switch Claude Account (Carry Context)',
    tooltip: 'Switch Claude account, carrying context over',
    detailEn: 'Moves the current conversation to a different Claude account profile while preserving context (useful for separate billing/orgs).',
    detailHe: 'מעביר את השיחה הנוכחית לפרופיל חשבון Claude אחר תוך שמירת ההקשר (שימושי לחיוב/ארגונים נפרדים).',
  },
  {
    id: 'commands-new-claude-tab-with-account',
    section: 'commands',
    name: 'ClaUi: New Claude Tab With Account',
    tooltip: 'Open a new Claude tab with a chosen account',
    detailEn: 'Opens a fresh Claude tab bound to a specific account profile you pick.',
    detailHe: 'פותח לשונית Claude חדשה הקשורה לפרופיל חשבון מסוים שתבחר.',
  },
  {
    id: 'commands-claude-accounts-manage',
    section: 'commands',
    name: 'ClaUi: Manage Claude Accounts',
    tooltip: 'Manage saved Claude accounts',
    detailEn: 'Opens the account manager to add, rename, or remove stored Claude account profiles.',
    detailHe: 'פותח את מנהל החשבונות להוספה, שינוי שם או הסרה של פרופילי חשבון Claude שמורים.',
  },
  {
    id: 'commands-claude-accounts-login',
    section: 'commands',
    name: 'ClaUi: Claude Account Login',
    tooltip: 'Log in to a Claude account',
    detailEn: 'Starts the login flow for a Claude account profile.',
    detailHe: 'מתחיל את זרימת ההתחברות לפרופיל חשבון Claude.',
  },
  {
    id: 'commands-claude-accounts-logout',
    section: 'commands',
    name: 'ClaUi: Claude Account Logout',
    tooltip: 'Log out of a Claude account',
    detailEn: 'Logs out the selected Claude account profile.',
    detailHe: 'מנתק את פרופיל חשבון Claude הנבחר.',
  },
  {
    id: 'commands-carry-codex-to-claude-code',
    section: 'commands',
    name: 'ClaUi: Carry Codex Session to Claude Code',
    tooltip: 'Hand a Codex session over to Claude Code',
    detailEn: 'Packages the current Codex conversation and continues it in a Claude Code session, carrying the context across.',
    detailHe: 'אורז את שיחת ה-Codex הנוכחית וממשיך אותה בסשן Claude Code, תוך העברת ההקשר.',
  },
  {
    id: 'commands-create-multi-participant-session',
    section: 'commands',
    name: 'ClaUi: Create Multi-Participant Session',
    tooltip: 'Create a shared multi-participant session',
    detailEn: 'Creates a new shared room (by name + number) where several humans, each with their own agent, collaborate through a coordination server.',
    detailHe: 'יוצר חדר משותף חדש (לפי שם + מספר) שבו כמה אנשים, כל אחד עם הסוכן שלו, משתפים פעולה דרך שרת תיאום.',
  },
  {
    id: 'commands-join-multi-participant-session',
    section: 'commands',
    name: 'ClaUi: Join Multi-Participant Session',
    tooltip: 'Join an existing shared session by number',
    detailEn: 'Joins an existing multi-participant room by its session number.',
    detailHe: 'מצטרף לחדר ריבוי-משתתפים קיים לפי מספר הסשן שלו.',
  },
  {
    id: 'commands-leave-multi-participant-session',
    section: 'commands',
    name: 'ClaUi: Leave Multi-Participant Session',
    tooltip: 'Leave the shared session',
    detailEn: 'Disconnects you from the current multi-participant room.',
    detailHe: 'מנתק אותך מחדר ריבוי-המשתתפים הנוכחי.',
  },
  {
    id: 'commands-tabs-focus',
    section: 'commands',
    name: 'ClaUi: Focus Tab',
    tooltip: 'Focus a specific tab',
    detailEn: 'Brings the specified ClaUi tab into focus (used by the tab rail and programmatic navigation).',
    detailHe: 'מביא את לשונית ClaUi שצוינה למיקוד (משמש את מסילת הלשוניות וניווט תוכניתי).',
  },
  {
    id: 'commands-tabs-close',
    section: 'commands',
    name: 'ClaUi: Close Tab',
    tooltip: 'Close a tab',
    detailEn: 'Closes the specified ClaUi tab and disposes its session resources.',
    detailHe: 'סוגר את לשונית ClaUi שצוינה ומשחרר את משאבי הסשן שלה.',
  },
  {
    id: 'commands-tabs-reorder',
    section: 'commands',
    name: 'ClaUi: Reorder Tabs',
    tooltip: 'Reorder tabs',
    detailEn: 'Applies a new ordering to ClaUi tabs (backs the drag-to-reorder rail).',
    detailHe: 'מחיל סדר חדש על לשוניות ClaUi (עומד מאחורי מסילת הגרירה-לסידור).',
  },
  {
    id: 'commands-tabs-move-to-group',
    section: 'commands',
    name: 'ClaUi: Move Tab to Folder',
    tooltip: 'Move a tab into a folder',
    detailEn: 'Moves a given tab into a chosen folder/group in the Sessions tree.',
    detailHe: 'מעביר לשונית נתונה לתיקייה/קבוצה נבחרת בעץ הסשנים.',
  },
  {
    id: 'commands-tabs-remove-from-group',
    section: 'commands',
    name: 'ClaUi: Remove Tab from Folder',
    tooltip: 'Remove a tab from its folder',
    detailEn: 'Removes a given tab from its folder, returning it to the top level.',
    detailHe: 'מסיר לשונית נתונה מהתיקייה שלה ומחזיר אותה לרמה העליונה.',
  },
  {
    id: 'commands-tabs-move-active-to-group',
    section: 'commands',
    name: 'ClaUi: Move This Tab to Folder',
    tooltip: 'Move the active tab into a folder',
    detailEn: 'Same as Move-to-Folder, applied to the currently active tab.',
    detailHe: 'כמו העברה-לתיקייה, מוחל על הלשונית הפעילה כעת.',
  },
  {
    id: 'commands-tabs-remove-active-from-group',
    section: 'commands',
    name: 'ClaUi: Remove This Tab from Folder',
    tooltip: 'Remove the active tab from its folder',
    detailEn: 'Same as Remove-from-Folder, applied to the currently active tab.',
    detailHe: 'כמו הסרה-מתיקייה, מוחל על הלשונית הפעילה כעת.',
  },
  {
    id: 'commands-tabs-open-layout-menu',
    section: 'commands',
    name: 'ClaUi: Tab Layout Settings',
    tooltip: 'Tab layout settings',
    detailEn: 'Opens a QuickPick to choose horizontal vs. vertical tab layout (also reachable from the Status Bar and Settings).',
    detailHe: 'פותח QuickPick לבחירה בין פריסת לשוניות אופקית לאנכית (נגיש גם מה-Status Bar ומההגדרות).',
  },
  {
    id: 'commands-groups-create',
    section: 'commands',
    name: 'ClaUi: New Folder',
    tooltip: 'Create a new folder',
    detailEn: 'Creates a new top-level folder in the Sessions tree to organize tabs.',
    detailHe: 'יוצר תיקייה חדשה ברמה העליונה בעץ הסשנים לארגון לשוניות.',
  },
  {
    id: 'commands-groups-create-subfolder',
    section: 'commands',
    name: 'ClaUi: New Sub-folder',
    tooltip: 'Create a sub-folder',
    detailEn: 'Creates a nested folder inside an existing folder.',
    detailHe: 'יוצר תיקייה מקוננת בתוך תיקייה קיימת.',
  },
  {
    id: 'commands-groups-rename',
    section: 'commands',
    name: 'ClaUi: Rename Folder',
    tooltip: 'Rename a folder',
    detailEn: 'Renames the selected folder.',
    detailHe: 'משנה את שם התיקייה הנבחרת.',
  },
  {
    id: 'commands-groups-change-color',
    section: 'commands',
    name: 'ClaUi: Change Folder Color',
    tooltip: "Change a folder's color",
    detailEn: 'Picks a new color for the folder; member tabs recolor their native VS Code tab icons to match.',
    detailHe: 'בוחר צבע חדש לתיקייה; הלשוניות החברות צובעות מחדש את אייקוני הלשונית המקוריים של VS Code בהתאמה.',
  },
  {
    id: 'commands-groups-delete',
    section: 'commands',
    name: 'ClaUi: Delete Folder',
    tooltip: 'Delete a folder',
    detailEn: 'Deletes the folder, prompting whether to cascade-delete its tabs or reparent them to the top level.',
    detailHe: 'מוחק את התיקייה, ושואל אם למחוק גם את הלשוניות שבה או להעבירן לרמה העליונה.',
  },

  // ===== Part 2 — Status Bar =====
  // Session group
  {
    id: 'statusbar-history',
    section: 'statusbar',
    name: 'History',
    tooltip: 'Conversation History (Ctrl+Shift+H)',
    detailEn: 'Open the conversation-history browser.',
    detailHe: 'פתח את דפדפן היסטוריית השיחות.',
  },
  {
    id: 'statusbar-plans',
    section: 'statusbar',
    name: 'Plans',
    tooltip: 'Open plan document in browser',
    detailEn: 'Open the Plan Mode document full-page.',
    detailHe: 'פתח את מסמך מצב Plan במסך מלא.',
  },
  {
    id: 'statusbar-prompts',
    section: 'statusbar',
    name: 'Prompts',
    tooltip: 'Prompt History',
    detailEn: 'Browse and reuse your previous prompts.',
    detailHe: 'עיין ומחזר פקודות קודמות שלך.',
  },
  {
    id: 'statusbar-search',
    section: 'statusbar',
    name: 'Search',
    tooltip: 'Search chat messages (Ctrl+Shift+F)',
    detailEn: 'Open the in-chat search bar.',
    detailHe: "פתח את שורת החיפוש בתוך הצ'אט.",
  },
  {
    id: 'statusbar-multi-participant',
    section: 'statusbar',
    name: 'Multi-Participant',
    detailEn: 'Open the shared multi-participant session view.',
    detailHe: 'פתח את תצוגת סשן ריבוי-המשתתפים המשותף.',
  },
  {
    id: 'statusbar-dashboard',
    section: 'statusbar',
    name: 'Dashboard',
    tooltip: 'Analytics Dashboard',
    detailEn: 'Open the analytics dashboard (usage, tools, tokens).',
    detailHe: 'פתח את לוח האנליטיקה (שימוש, כלים, טוקנים).',
  },
  {
    id: 'statusbar-workstream-map',
    section: 'statusbar',
    name: 'Workstream Map',
    tooltip: 'Workstream Map',
    detailEn: 'Open the visual map of sessions/branches.',
    detailHe: 'פתח את המפה הוויזואלית של סשנים/ענפים.',
  },
  {
    id: 'statusbar-worktrees',
    section: 'statusbar',
    name: 'Worktrees',
    tooltip: 'Git worktrees dashboard…',
    detailEn: 'Open the worktrees dashboard.',
    detailHe: 'פתח את לוח ה-worktrees.',
  },
  {
    id: 'statusbar-teams',
    section: 'statusbar',
    name: 'Teams',
    tooltip: 'Agent Teams Panel',
    detailEn: 'Open the Agent Teams panel (shown when a team is active).',
    detailHe: 'פתח את פאנל צוותי הסוכנים (מוצג כשצוות פעיל).',
  },
  {
    id: 'statusbar-achievements-count',
    section: 'statusbar',
    name: '🏆 count',
    detailEn: 'Open the Achievements panel (shown when achievements are enabled).',
    detailHe: 'פתח את פאנל ההישגים (מוצג כשההישגים מופעלים).',
  },
  // Tools group
  {
    id: 'statusbar-git',
    section: 'statusbar',
    name: 'Git',
    tooltip: 'Git: add, commit & push / setup needed',
    detailEn: 'One-click stage+commit+push; opens setup if not configured.',
    detailHe: 'הוספה+commit+push בלחיצה; פותח הגדרה אם לא הוגדר.',
  },
  {
    id: 'statusbar-git-settings',
    section: 'statusbar',
    name: 'Git *',
    tooltip: 'Git push settings',
    detailEn: 'Open Git push settings panel.',
    detailHe: 'פתח את פאנל הגדרות ה-Git push.',
  },
  {
    id: 'statusbar-snippet',
    section: 'statusbar',
    name: 'Snippet',
    tooltip: 'Insert snippet at cursor / set it up',
    detailEn: 'Insert your saved snippet; opens config if empty.',
    detailHe: 'הכנס את ה-snippet השמור; פותח הגדרה אם ריק.',
  },
  {
    id: 'statusbar-snippet-edit',
    section: 'statusbar',
    name: 'Snippet *',
    tooltip: 'Edit custom snippet text',
    detailEn: 'Open the snippet editor.',
    detailHe: 'פתח את עורך ה-snippet.',
  },
  {
    id: 'statusbar-consult-codex',
    section: 'statusbar',
    name: 'Consult Codex',
    tooltip: 'Consult Codex GPT expert',
    detailEn: 'Ask a Codex/GPT expert about the current work.',
    detailHe: 'התייעץ עם מומחה Codex/GPT לגבי העבודה הנוכחית.',
  },
  {
    id: 'statusbar-run-review-now',
    section: 'statusbar',
    name: 'Run Review Now',
    tooltip: 'Run a Claude + Codex review now',
    detailEn: 'Launch a one-off Claude+Codex review (when auto-review is off).',
    detailHe: 'הפעל סקירת Claude+Codex חד-פעמית (כשאוטו-סקירה כבויה).',
  },
  {
    id: 'statusbar-auto-review-toggle',
    section: 'statusbar',
    name: 'Auto-review toggle',
    tooltip: 'Auto-start the review loop after each work turn',
    detailEn: 'Global default: auto-run review after every turn.',
    detailHe: 'ברירת מחדל גלובלית: הרצת סקירה אוטומטית אחרי כל תור.',
  },
  {
    id: 'statusbar-auto-review-skip-session',
    section: 'statusbar',
    name: 'Auto-review (skip session)',
    tooltip: 'Skip auto-review for THIS session only',
    detailEn: 'Turn off auto-review for the current session only.',
    detailHe: 'כבה אוטו-סקירה עבור הסשן הנוכחי בלבד.',
  },
  {
    id: 'statusbar-auto-review-launch-now',
    section: 'statusbar',
    name: 'Auto-review (launch now)',
    tooltip: 'Launch a review loop for the current session now!',
    detailEn: 'Start a review loop immediately.',
    detailHe: 'הפעל לולאת סקירה מיד.',
  },
  {
    id: 'statusbar-goal',
    section: 'statusbar',
    name: 'Goal',
    tooltip: 'Set autonomous goal / Goal active…',
    detailEn: 'Set an objective the AI works toward autonomously.',
    detailHe: 'הגדר יעד שה-AI עובד להשגתו באופן אוטונומי.',
  },
  {
    id: 'statusbar-smart-search',
    section: 'statusbar',
    name: 'Smart Search (Opus/Sonnet/Haiku/GPT…)',
    tooltip: 'Search past sessions using <model>',
    detailEn: 'Open Smart Search with the chosen model.',
    detailHe: 'פתח Smart Search עם המודל הנבחר.',
  },
  {
    id: 'statusbar-babel-fish',
    section: 'statusbar',
    name: 'Babel Fish',
    tooltip: 'Babel Fish translation settings',
    detailEn: 'Open translation settings for messages.',
    detailHe: 'פתח את הגדרות התרגום להודעות.',
  },
  {
    id: 'statusbar-skilldocs',
    section: 'statusbar',
    name: 'SkillDocs n/N',
    detailEn: 'Open the Skill generation panel.',
    detailHe: 'פתח את פאנל יצירת ה-Skills.',
  },
  {
    id: 'statusbar-skilldocs-info',
    section: 'statusbar',
    name: 'SkillDocs !',
    tooltip: 'How Skills work',
    detailEn: 'Open the Skills info/help.',
    detailHe: 'פתח מידע/עזרה על Skills.',
  },
  {
    id: 'statusbar-report-bug',
    section: 'statusbar',
    name: 'Report Bug',
    tooltip: 'Open bug report',
    detailEn: 'Open the bug-report form.',
    detailHe: 'פתח את טופס דיווח הבאג.',
  },
  {
    id: 'statusbar-feature-request',
    section: 'statusbar',
    name: 'Feature Request',
    tooltip: 'Request a new feature',
    detailEn: 'Open the feature-request form.',
    detailHe: "פתח את טופס בקשת הפיצ'ר.",
  },
  {
    id: 'statusbar-email-feedback',
    section: 'statusbar',
    name: 'Email Feedback',
    tooltip: 'Send email feedback',
    detailEn: 'Send feedback by email.',
    detailHe: 'שלח משוב באימייל.',
  },
  {
    id: 'statusbar-full-bug-report',
    section: 'statusbar',
    name: 'Full Bug Report',
    tooltip: 'Collect diagnostics and send full report',
    detailEn: 'Gather diagnostics and submit a full report.',
    detailHe: 'אסוף דיאגנוסטיקה ושלח דוח מלא.',
  },
  // View group + right-side metrics
  {
    id: 'statusbar-vitals',
    section: 'statusbar',
    name: 'Vitals',
    tooltip: 'Show/Hide Session Vitals',
    detailEn: 'Toggle the floating Session Vitals widget.',
    detailHe: "הפעל/כבה את ווידג'ט ה-Session Vitals הצף.",
  },
  {
    id: 'statusbar-vitals-settings',
    section: 'statusbar',
    name: 'Vitals ⚙',
    tooltip: 'Vitals settings',
    detailEn: 'Open Vitals settings.',
    detailHe: 'פתח את הגדרות ה-Vitals.',
  },
  {
    id: 'statusbar-tab-layout',
    section: 'statusbar',
    name: 'Horizontal / Vertical',
    detailEn: 'Choose horizontal or vertical tab layout.',
    detailHe: 'בחר פריסת לשוניות אופקית או אנכית.',
  },
  {
    id: 'statusbar-usage-metric',
    section: 'statusbar',
    name: 'Usage metric',
    tooltip: 'Usage Data',
    detailEn: 'Open the subscription usage popover.',
    detailHe: 'פתח את חלונית נתוני השימוש במנוי.',
  },
  {
    id: 'statusbar-usage-refresh',
    section: 'statusbar',
    name: 'Usage ↻',
    tooltip: 'Refresh',
    detailEn: 'Refresh usage data.',
    detailHe: 'רענן את נתוני השימוש.',
  },
  {
    id: 'statusbar-show-hide-strip',
    section: 'statusbar',
    name: 'Show/Hide strip',
    tooltip: 'Show/Hide context strip',
    detailEn: 'Toggle the context-usage strip above the input.',
    detailHe: 'הפעל/כבה את פס ניצול-ההקשר מעל הקלט.',
  },
  {
    id: 'statusbar-session-clock',
    section: 'statusbar',
    name: 'Session clock',
    tooltip: 'Claude active processing time…',
    detailEn: 'Live timer of active processing since first prompt.',
    detailHe: 'טיימר חי של זמן עיבוד פעיל מאז הפקודה הראשונה.',
  },
  {
    id: 'statusbar-mcp-chip',
    section: 'statusbar',
    name: 'MCP chip',
    tooltip: 'Open MCP inventory',
    detailEn: 'Open the MCP servers panel.',
    detailHe: 'פתח את פאנל שרתי ה-MCP.',
  },
  {
    id: 'statusbar-send-capsule-manually',
    section: 'statusbar',
    name: 'Send capsule manually',
    tooltip: 'Copy capsule prompt for manual send',
    detailEn: '(Handoff fallback) copy the context capsule to send by hand.',
    detailHe: '(גיבוי handoff) העתק את קפסולת ההקשר לשליחה ידנית.',
  },

  // ===== Part 3 — Input Area =====
  {
    id: 'inputarea-search-chat',
    section: 'inputarea',
    name: '🔍 Search chat',
    tooltip: 'Search chat (Ctrl+Shift+F)',
    detailEn: 'Toggle the in-chat search bar.',
    detailHe: "הפעל/כבה את שורת החיפוש בצ'אט.",
  },
  {
    id: 'inputarea-clear',
    section: 'inputarea',
    name: 'Clear',
    tooltip: 'Clear session and start fresh',
    detailEn: 'Reset the conversation and restart the session.',
    detailHe: 'אפס את השיחה והפעל מחדש את הסשן.',
  },
  {
    id: 'inputarea-ultrathink-lock',
    section: 'inputarea',
    name: 'Ultrathink lock 🔒',
    tooltip: 'Lock ultrathink on every prompt',
    detailEn: 'Keep "ultrathink" prepended to every prompt.',
    detailHe: 'שמור על "ultrathink" בתחילת כל פקודה.',
  },
  {
    id: 'inputarea-ultrathink',
    section: 'inputarea',
    name: 'Ultrathink ⚡',
    tooltip: 'Ultrathink – boost reasoning power',
    detailEn: 'Cycle ultrathink off → single → locked.',
    detailHe: 'החלף ultrathink כבוי → חד-פעמי → נעול.',
  },
  {
    id: 'inputarea-browse',
    section: 'inputarea',
    name: 'Browse 📎',
    tooltip: 'Browse files to paste their paths',
    detailEn: 'Open the file picker to insert file paths.',
    detailHe: 'פתח את בורר הקבצים להכנסת נתיבי קבצים.',
  },
  {
    id: 'inputarea-enhance',
    section: 'inputarea',
    name: 'Enhance ✨',
    tooltip: 'Enhance prompt (Ctrl+Shift+E)',
    detailEn: 'Rewrite/improve the current prompt via AI.',
    detailHe: 'שכתב/שפר את הפקודה הנוכחית בעזרת AI.',
  },
  {
    id: 'inputarea-enhance-settings',
    section: 'inputarea',
    name: 'Enhance ⚙',
    tooltip: 'Enhancer settings',
    detailEn: 'Open enhancer settings (auto-enhance, model).',
    detailHe: 'פתח הגדרות שיפור (אוטו-שיפור, מודל).',
  },
  {
    id: 'inputarea-cancel-stop',
    section: 'inputarea',
    name: 'Cancel / Stop',
    tooltip: 'Cancel current response (Esc)',
    detailEn: 'Interrupt the in-flight response (or steer Codex).',
    detailHe: 'קטע את התגובה המתבצעת (או הכוון את Codex).',
  },
  {
    id: 'inputarea-prompt-navigation',
    section: 'inputarea',
    name: '▲▲ / ▲ / ▼ / ▼▼',
    tooltip: 'Jump/prev/next/jump prompt navigation',
    detailEn: 'Navigate between user prompts / conversation edges.',
    detailHe: 'נווט בין פקודות המשתמש / קצוות השיחה.',
  },
  {
    id: 'inputarea-send',
    section: 'inputarea',
    name: 'Send',
    tooltip: 'Send message (Ctrl+Enter)',
    detailEn: 'Send the message (label changes: Steer/Schedule/Translate).',
    detailHe: 'שלח את ההודעה (התווית משתנה: Steer/Schedule/Translate).',
  },
  {
    id: 'inputarea-send-settings',
    section: 'inputarea',
    name: 'Send ⚙',
    tooltip: 'Send settings',
    detailEn: 'Open send settings (translate, auto-send, schedule).',
    detailHe: 'פתח הגדרות שליחה (תרגום, אוטו-שליחה, תזמון).',
  },
  {
    id: 'inputarea-popover-toggles',
    section: 'inputarea',
    name: 'Toggles in popovers',
    tooltip: 'Enable/Disable <feature>',
    detailEn: 'Toggle auto-enhance / translation / auto-send / scheduling.',
    detailHe: 'הפעל/כבה אוטו-שיפור / תרגום / אוטו-שליחה / תזמון.',
  },
  {
    id: 'inputarea-remove-image',
    section: 'inputarea',
    name: 'Remove image x',
    tooltip: 'Remove image',
    detailEn: 'Remove a pending pasted image.',
    detailHe: 'הסר תמונה ממתינה שהודבקה.',
  },
  {
    id: 'inputarea-cancel-scheduled',
    section: 'inputarea',
    name: 'Cancel scheduled',
    tooltip: 'Cancel scheduled message',
    detailEn: 'Cancel a queued/scheduled message.',
    detailHe: 'בטל הודעה מתוזמנת/בתור.',
  },
  {
    id: 'inputarea-goal-clear',
    section: 'inputarea',
    name: 'Goal clear x',
    tooltip: 'Clear goal (/goal clear)',
    detailEn: 'Clear the active autonomous goal.',
    detailHe: 'נקה את היעד האוטונומי הפעיל.',
  },

  // ===== Part 4 — App-level controls =====
  {
    id: 'app-start-session-welcome',
    section: 'app',
    name: 'Start Session (welcome)',
    tooltip: 'Start a new Claude Code session',
    detailEn: 'Start the first session from the welcome screen.',
    detailHe: 'התחל את הסשן הראשון ממסך הפתיחה.',
  },
  {
    id: 'app-conversation-history-welcome',
    section: 'app',
    name: 'Conversation History (welcome)',
    tooltip: 'Browse previous conversations',
    detailEn: 'Open conversation history.',
    detailHe: 'פתח את היסטוריית השיחות.',
  },
  {
    id: 'app-new-session-ended-bar',
    section: 'app',
    name: 'New Session (ended bar)',
    tooltip: 'Start a new session',
    detailEn: 'Restart after a session ends.',
    detailHe: 'הפעל מחדש לאחר סיום סשן.',
  },
  {
    id: 'app-history-ended-bar',
    section: 'app',
    name: 'History (ended bar)',
    tooltip: 'Browse previous conversations',
    detailEn: 'Open conversation history.',
    detailHe: 'פתח את היסטוריית השיחות.',
  },
  {
    id: 'app-switch-to-codex',
    section: 'app',
    name: 'Switch to Codex',
    tooltip: 'Open a Codex tab and use Codex instead of Claude',
    detailEn: '(Claude-missing banner) fall back to Codex.',
    detailHe: '(באנר Claude חסר) מעבר ל-Codex.',
  },
  {
    id: 'app-copy-install-command',
    section: 'app',
    name: 'Copy Install Command',
    tooltip: 'Copies: npm install -g @anthropic-ai/claude-code',
    detailEn: 'Copy the Claude CLI install command.',
    detailHe: 'העתק את פקודת ההתקנה של Claude CLI.',
  },
  {
    id: 'app-claude-code-docs',
    section: 'app',
    name: 'Claude Code Docs',
    tooltip: 'Open the Claude Code documentation in your browser',
    detailEn: 'Open the docs site.',
    detailHe: 'פתח את אתר התיעוד.',
  },
  {
    id: 'app-set-cli-path',
    section: 'app',
    name: 'Set CLI Path',
    tooltip: 'Open settings to set the path to the claude executable',
    detailEn: 'Jump to the CLI-path setting.',
    detailHe: 'קפוץ להגדרת נתיב ה-CLI.',
  },
  {
    id: 'app-auto-setup-codex-cli',
    section: 'app',
    name: 'Auto-setup Codex CLI',
    tooltip: 'Automatically install and configure the Codex CLI',
    detailEn: 'Run automated Codex setup.',
    detailHe: 'הרץ התקנת Codex אוטומטית.',
  },
  {
    id: 'app-auto-detect-codex-cli',
    section: 'app',
    name: 'Auto-detect Codex CLI',
    tooltip: 'Search common locations for an existing codex executable',
    detailEn: 'Detect an installed codex binary.',
    detailHe: 'אתר קובץ codex מותקן.',
  },
  {
    id: 'app-open-install-guide',
    section: 'app',
    name: 'Open Install Guide',
    tooltip: 'Open the Codex install guide on GitHub',
    detailEn: 'Open Codex install docs.',
    detailHe: 'פתח את תיעוד התקנת Codex.',
  },
  {
    id: 'app-browse-for-codex-executable',
    section: 'app',
    name: 'Browse for codex executable',
    tooltip: 'Pick the codex executable manually with a file dialog',
    detailEn: 'Pick the codex binary by hand.',
    detailHe: 'בחר ידנית את קובץ codex.',
  },
  {
    id: 'app-open-codex-path-setting',
    section: 'app',
    name: 'Open Codex Path Setting',
    tooltip: 'Open settings to set the Codex CLI path',
    detailEn: 'Jump to the Codex-path setting.',
    detailHe: 'קפוץ להגדרת נתיב Codex.',
  },
  {
    id: 'app-open-setup-login-terminal',
    section: 'app',
    name: 'Open Setup/Login Terminal',
    tooltip: 'Open a terminal to install or sign in to Codex',
    detailEn: 'Open a terminal for Codex setup/login.',
    detailHe: 'פתח טרמינל להתקנה/התחברות ל-Codex.',
  },
  {
    id: 'app-dismiss-banners',
    section: 'app',
    name: 'Dismiss (banners)',
    tooltip: 'Dismiss this notice',
    detailEn: 'Hide the setup banner.',
    detailHe: 'הסתר את באנר ההתקנה.',
  },
  {
    id: 'app-show-more-less',
    section: 'app',
    name: 'Show more / Show less',
    tooltip: 'Show the full / Collapse the error message',
    detailEn: 'Expand or collapse a long error.',
    detailHe: 'הרחב או כווץ שגיאה ארוכה.',
  },
  {
    id: 'app-dismiss-error',
    section: 'app',
    name: 'Dismiss (error x)',
    tooltip: 'Dismiss',
    detailEn: 'Clear the error banner.',
    detailHe: 'נקה את באנר השגיאה.',
  },
  {
    id: 'app-disable-permanently',
    section: 'app',
    name: 'Disable permanently',
    tooltip: 'Never show the live activity summary again',
    detailEn: 'Permanently disable the activity summary.',
    detailHe: 'כבה לצמיתות את סיכום הפעילות החי.',
  },
  {
    id: 'app-session-summary-nudge',
    section: 'app',
    name: 'Session Summary (nudge)',
    tooltip: 'Generate a summary of this session so far',
    detailEn: 'Produce a session recap.',
    detailHe: 'הפק תקציר סשן.',
  },
  {
    id: 'app-later-nudge',
    section: 'app',
    name: 'Later (nudge)',
    tooltip: 'Hide this nudge and ask again later',
    detailEn: 'Defer the summary nudge.',
    detailHe: 'דחה את ההצעה לסיכום.',
  },
  {
    id: 'app-dismiss-nudge',
    section: 'app',
    name: 'Dismiss (nudge)',
    tooltip: 'Dismiss this nudge',
    detailEn: 'Hide the summary nudge.',
    detailHe: 'הסתר את ההצעה לסיכום.',
  },

  // ===== Part 5 — Chat View =====
  // Message bubble actions
  {
    id: 'chatview-copy',
    section: 'chatview',
    name: 'Copy',
    tooltip: 'Copy to clipboard',
    detailEn: 'Copy the message text.',
    detailHe: 'העתק את טקסט ההודעה.',
  },
  {
    id: 'chatview-auto-ltr',
    section: 'chatview',
    name: 'Auto / LTR',
    tooltip: 'Force left alignment / Restore automatic alignment',
    detailEn: 'Toggle forced left-to-right alignment for this message.',
    detailHe: 'החלף יישור-לשמאל כפוי עבור ההודעה הזו.',
  },
  {
    id: 'chatview-expand-collapse-all',
    section: 'chatview',
    name: 'Expand/collapse all',
    tooltip: 'Expand/Collapse all blocks',
    detailEn: 'Open or close every tool block in the message.',
    detailHe: 'פתח או סגור את כל בלוקי הכלים בהודעה.',
  },
  {
    id: 'chatview-edit',
    section: 'chatview',
    name: 'Edit',
    tooltip: 'Edit and resend this message',
    detailEn: 'Edit a user message and resend it.',
    detailHe: 'ערוך הודעת משתמש ושלח אותה מחדש.',
  },
  {
    id: 'chatview-fork',
    section: 'chatview',
    name: 'Fork',
    tooltip: 'Fork conversation from this message',
    detailEn: 'Branch a new conversation from this point.',
    detailHe: 'פצל שיחה חדשה מנקודה זו.',
  },
  {
    id: 'chatview-revert',
    section: 'chatview',
    name: 'Revert',
    tooltip: 'Revert file changes from this prompt onwards',
    detailEn: 'Undo file changes made from this prompt onward.',
    detailHe: 'בטל שינויי קבצים שבוצעו מפקודה זו והלאה.',
  },
  {
    id: 'chatview-redo',
    section: 'chatview',
    name: 'Redo',
    tooltip: 'Re-apply file changes',
    detailEn: 'Re-apply previously reverted file changes.',
    detailHe: 'החל מחדש שינויי קבצים שבוטלו.',
  },
  {
    id: 'chatview-translate',
    section: 'chatview',
    name: 'Translate',
    detailEn: 'Translate the message or toggle original/translated.',
    detailHe: 'תרגם את ההודעה או החלף בין מקור/תרגום.',
  },
  {
    id: 'chatview-send-edit',
    section: 'chatview',
    name: 'Send (edit)',
    tooltip: 'Send edited message',
    detailEn: 'Send the edited message.',
    detailHe: 'שלח את ההודעה הערוכה.',
  },
  {
    id: 'chatview-cancel-edit',
    section: 'chatview',
    name: 'Cancel (edit)',
    tooltip: 'Cancel editing',
    detailEn: 'Discard the edit.',
    detailHe: 'בטל את העריכה.',
  },
  // Code, tool, agent & team blocks
  {
    id: 'chatview-preview-codeblock',
    section: 'chatview',
    name: 'Preview (CodeBlock)',
    tooltip: 'Preview rendered HTML',
    detailEn: 'Render an HTML code block in a preview.',
    detailHe: 'רנדר בלוק קוד HTML בתצוגה מקדימה.',
  },
  {
    id: 'chatview-copy-codeblock',
    section: 'chatview',
    name: 'Copy (CodeBlock)',
    tooltip: 'Copy to clipboard',
    detailEn: 'Copy the code.',
    detailHe: 'העתק את הקוד.',
  },
  {
    id: 'chatview-show-more-less-codeblock',
    section: 'chatview',
    name: 'Show more/less (CodeBlock)',
    tooltip: 'Expand/Collapse code block',
    detailEn: 'Expand or collapse a long code block.',
    detailHe: 'הרחב או כווץ בלוק קוד ארוך.',
  },
  {
    id: 'chatview-tool-header',
    section: 'chatview',
    name: 'Tool header (ToolUseBlock)',
    tooltip: 'Click to expand/collapse',
    detailEn: 'Toggle a tool-use block open/closed.',
    detailHe: 'פתח/סגור בלוק שימוש-בכלי.',
  },
  {
    id: 'chatview-agent-header',
    section: 'chatview',
    name: 'Agent header (AgentSpawnBlock)',
    tooltip: 'Click to expand/collapse',
    detailEn: 'Toggle a spawned-agent block.',
    detailHe: 'פתח/סגור בלוק סוכן שהופעל.',
  },
  {
    id: 'chatview-team-header',
    section: 'chatview',
    name: 'Team header (TeamInlineWidget)',
    tooltip: 'Click to expand/collapse',
    detailEn: 'Toggle the inline team widget.',
    detailHe: "פתח/סגור את ווידג'ט הצוות המוטבע.",
  },
  {
    id: 'chatview-open-team-panel',
    section: 'chatview',
    name: 'Open Team Panel',
    tooltip: 'Open the Agent Teams management panel',
    detailEn: 'Open the full Agent Teams panel.',
    detailHe: 'פתח את פאנל צוותי הסוכנים המלא.',
  },
  // Plan Approval & Question bar
  {
    id: 'chatview-plan-option-1',
    section: 'chatview',
    name: 'Plan option 1',
    tooltip: 'Approve the plan, clear the context window, and stop asking permission for each action',
    detailEn: 'Approve + clear context + bypass permissions.',
    detailHe: 'אשר + נקה הקשר + עקוף הרשאות.',
  },
  {
    id: 'chatview-plan-option-2',
    section: 'chatview',
    name: 'Plan option 2',
    tooltip: 'Approve the plan and stop asking permission for each action',
    detailEn: 'Approve + bypass permissions.',
    detailHe: 'אשר + עקוף הרשאות.',
  },
  {
    id: 'chatview-plan-option-3',
    section: 'chatview',
    name: 'Plan option 3',
    tooltip: 'Approve the plan but review and confirm each edit manually',
    detailEn: 'Approve, confirm edits manually.',
    detailHe: 'אשר, אשר כל עריכה ידנית.',
  },
  {
    id: 'chatview-plan-option-4',
    section: 'chatview',
    name: 'Plan option 4',
    tooltip: 'Reject for now and type changes you want Claude to make',
    detailEn: 'Open free-text feedback.',
    detailHe: 'פתח משוב בטקסט חופשי.',
  },
  {
    id: 'chatview-question-option',
    section: 'chatview',
    name: 'Question option',
    detailEn: "Choose an answer to Claude's question.",
    detailHe: 'בחר תשובה לשאלת Claude.',
  },
  {
    id: 'chatview-submit-multi-select',
    section: 'chatview',
    name: 'Submit (multi-select)',
    tooltip: 'Submit your selected answers',
    detailEn: 'Submit multiple selected answers.',
    detailHe: 'שלח מספר תשובות נבחרות.',
  },
  {
    id: 'chatview-custom-answer',
    section: 'chatview',
    name: 'Custom answer…',
    tooltip: 'Write a free-text answer instead of choosing an option',
    detailEn: 'Type a custom answer.',
    detailHe: 'הקלד תשובה מותאמת אישית.',
  },
  {
    id: 'chatview-send-custom-answer',
    section: 'chatview',
    name: 'Send (custom answer)',
    tooltip: 'Send your custom answer (Enter)',
    detailEn: 'Send the typed answer.',
    detailHe: 'שלח את התשובה שהוקלדה.',
  },
  {
    id: 'chatview-send-plan-feedback',
    section: 'chatview',
    name: 'Send (plan feedback)',
    tooltip: 'Send your feedback to Claude (Enter)',
    detailEn: 'Send plan feedback.',
    detailHe: 'שלח משוב על התוכנית.',
  },
  // In-chat search & prompt history
  {
    id: 'chatview-search-scope',
    section: 'chatview',
    name: 'Session / Project (ChatSearchBar)',
    tooltip: 'Search current session / all project sessions',
    detailEn: 'Set the search scope.',
    detailHe: 'קבע את היקף החיפוש.',
  },
  {
    id: 'chatview-search-nav',
    section: 'chatview',
    name: '↑ / ↓ (ChatSearchBar)',
    tooltip: 'Previous/Next match (Shift+Enter / Enter)',
    detailEn: 'Jump between matches.',
    detailHe: 'קפוץ בין התאמות.',
  },
  {
    id: 'chatview-search-close',
    section: 'chatview',
    name: 'x (ChatSearchBar)',
    tooltip: 'Close (Esc)',
    detailEn: 'Close the search bar.',
    detailHe: 'סגור את שורת החיפוש.',
  },
  {
    id: 'chatview-prompt-history-close',
    section: 'chatview',
    name: 'x (PromptHistoryPanel)',
    tooltip: 'Close (Esc)',
    detailEn: 'Close the prompt history panel.',
    detailHe: 'סגור את פאנל היסטוריית הפקודות.',
  },
  {
    id: 'chatview-prompt-history-tabs',
    section: 'chatview',
    name: 'Session / Project / Global tabs',
    tooltip: 'Prompts from current session / all sessions / all projects',
    detailEn: 'Choose which prompt-history scope to show.',
    detailHe: 'בחר את היקף היסטוריית הפקודות להצגה.',
  },
  {
    id: 'chatview-prompt-item',
    section: 'chatview',
    name: 'Prompt item',
    detailEn: 'Insert a past prompt into the input.',
    detailHe: 'הכנס פקודה קודמת לקלט.',
  },
  // Links, scroll & "btw…" side-thought
  {
    id: 'chatview-scroll-to-bottom',
    section: 'chatview',
    name: 'Scroll to bottom (MessageList)',
    tooltip: 'Scroll to bottom',
    detailEn: 'Jump to the latest message.',
    detailHe: 'קפוץ להודעה האחרונה.',
  },
  {
    id: 'chatview-open-session',
    section: 'chatview',
    name: 'Open session → (MarkdownContent)',
    tooltip: 'Open this session in a new ClaUi tab',
    detailEn: 'Open a Smart Search result session.',
    detailHe: 'פתח סשן מתוצאת Smart Search.',
  },
  {
    id: 'chatview-file-url-link',
    section: 'chatview',
    name: 'File path / URL link (filePathLinks)',
    tooltip: 'Click to open …',
    detailEn: 'Open a file in the editor / a URL in the browser.',
    detailHe: 'פתח קובץ בעורך / כתובת בדפדפן.',
  },
  {
    id: 'chatview-btw-context-menu',
    section: 'chatview',
    name: 'btw… (context menu)',
    tooltip: 'Start a side thought (by the way…)',
    detailEn: 'Open the btw compose popup.',
    detailHe: 'פתח את חלונית כתיבת ה-btw.',
  },
  {
    id: 'chatview-clipboard-context-menu',
    section: 'chatview',
    name: 'Copy link / Copy / Paste (context menu)',
    tooltip: 'Copy link / Copy selection / Paste from clipboard',
    detailEn: 'Clipboard actions in the custom context menu.',
    detailHe: 'פעולות לוח בתפריט ההקשר המותאם.',
  },
  {
    id: 'chatview-btw-new-tab',
    section: 'chatview',
    name: 'New Tab (btw compose)',
    tooltip: 'Open this side thought in a new tab',
    detailEn: 'Send the side thought to a new tab.',
    detailHe: 'שלח את מחשבת-הצד ללשונית חדשה.',
  },
  {
    id: 'chatview-btw-send-compose',
    section: 'chatview',
    name: 'Send (btw compose)',
    tooltip: 'Start a background BTW session (Ctrl+Enter)',
    detailEn: 'Run the side thought as a background session.',
    detailHe: 'הרץ את מחשבת-הצד כסשן רקע.',
  },
  {
    id: 'chatview-btw-cancel-compose',
    section: 'chatview',
    name: 'Cancel (btw compose)',
    tooltip: 'Cancel (Esc)',
    detailEn: 'Close the btw popup.',
    detailHe: 'סגור את חלונית ה-btw.',
  },
  {
    id: 'chatview-btw-send-chat',
    section: 'chatview',
    name: 'Send (btw chat)',
    tooltip: 'Send message (Enter)',
    detailEn: 'Send a message in the btw chat.',
    detailHe: 'שלח הודעה בצ\'אט ה-btw.',
  },
  {
    id: 'chatview-btw-close',
    section: 'chatview',
    name: 'Close (btw)',
    tooltip: 'Close',
    detailEn: 'Close the btw overlay.',
    detailHe: 'סגור את שכבת ה-btw.',
  },

  // ===== Part 6 — Feature panels =====
  // Analytics Dashboard
  {
    id: 'panels-dashboard-scope',
    section: 'panels',
    name: 'Session / Project / User',
    tooltip: 'Show <scope> analytics',
    detailEn: 'Switch the dashboard data scope.',
    detailHe: 'החלף את היקף נתוני הלוח.',
  },
  {
    id: 'panels-dashboard-tabs',
    section: 'panels',
    name: 'Tab buttons',
    tooltip: 'Open <tab> tab',
    detailEn: 'Navigate to a dashboard tab.',
    detailHe: 'נווט לתאב בלוח.',
  },
  {
    id: 'panels-dashboard-turntable-paginate',
    section: 'panels',
    name: 'Prev / Next (TurnTable)',
    tooltip: 'Previous / Next page',
    detailEn: 'Paginate the turns table.',
    detailHe: 'דפדוף בטבלת התורים.',
  },
  {
    id: 'panels-dashboard-category-chips',
    section: 'panels',
    name: 'Category chips (Commands)',
    tooltip: 'Toggle <category> commands',
    detailEn: 'Filter the command list.',
    detailHe: 'סנן את רשימת הפקודות.',
  },
  {
    id: 'panels-dashboard-context-chips',
    section: 'panels',
    name: 'Role chips / Expand All / Collapse All (Context)',
    tooltip: 'Show <role> messages / Expand / Collapse all messages',
    detailEn: 'Filter and expand context messages.',
    detailHe: 'סנן והרחב הודעות הקשר.',
  },
  {
    id: 'panels-dashboard-tokenratio',
    section: 'panels',
    name: 'Sample Points / time-range / Resample / Clear (TokenRatio)',
    tooltip: 'Toggle markers / Show <range> / Recompute now / Delete all data',
    detailEn: 'Control the token-ratio chart and data.',
    detailHe: 'שלוט בגרף יחס-הטוקנים ובנתונים.',
  },
  {
    id: 'panels-dashboard-tools-guard',
    section: 'panels',
    name: 'Guard On/Off, Add Folder, Add Workspace, Remove, Path, Command, Check (Tools)',
    tooltip: 'Toggle guard / add / remove / test access',
    detailEn: 'Manage the Workspace Access Guard allow-list and test it.',
    detailHe: 'נהל את רשימת-ההיתר של שומר הגישה ובדוק אותה.',
  },
  {
    id: 'panels-dashboard-usage',
    section: 'panels',
    name: 'Refresh / period tabs (Usage)',
    tooltip: 'Reload usage data / Show <period> usage',
    detailEn: 'Refresh and scope usage stats.',
    detailHe: 'רענן ובחר טווח לנתוני שימוש.',
  },
  // MCP panel
  {
    id: 'panels-mcp-refresh-close',
    section: 'panels',
    name: 'Refresh / Close',
    tooltip: 'Reload MCP inventory / Close MCP panel',
    detailEn: 'Refresh or close the panel.',
    detailHe: 'רענן או סגור את הפאנל.',
  },
  {
    id: 'panels-mcp-restart-apply-later',
    section: 'panels',
    name: 'Restart session / Apply later',
    tooltip: 'Restart to reload MCP / Postpone restart',
    detailEn: 'Apply MCP config changes now or later.',
    detailHe: 'החל שינויי MCP עכשיו או מאוחר יותר.',
  },
  {
    id: 'panels-mcp-tabs',
    section: 'panels',
    name: 'Tabs (Session/Workspace/Add/Debug)',
    tooltip: 'Switch <tab>',
    detailEn: 'Navigate MCP panel tabs.',
    detailHe: 'נווט בין תאבי פאנל ה-MCP.',
  },
  {
    id: 'panels-mcp-add-wizard',
    section: 'panels',
    name: 'Preview / Add server (Add wizard)',
    tooltip: 'Preview the .mcp.json diff / Save the server',
    detailEn: 'Preview config and add a server.',
    detailHe: 'תצוגה מקדימה והוספת שרת.',
  },
  {
    id: 'panels-mcp-debug',
    section: 'panels',
    name: 'Open / Copy / Reset approvals (Debug)',
    tooltip: 'Open config / Copy command / Clear approvals',
    detailEn: 'Debug MCP config and approvals.',
    detailHe: 'תחקור הגדרות ואישורי MCP.',
  },
  {
    id: 'panels-mcp-workspace',
    section: 'panels',
    name: 'Open config / Remove (Workspace)',
    tooltip: 'Open config file / Remove server',
    detailEn: 'Manage workspace MCP servers.',
    detailHe: 'נהל שרתי MCP של סביבת העבודה.',
  },
  {
    id: 'panels-mcp-quickadd',
    section: 'panels',
    name: 'Import / Template / Custom (QuickAdd)',
    tooltip: 'Import from Claude Desktop / Add <template> / Add custom server',
    detailEn: 'Quick-add MCP servers.',
    detailHe: 'הוספה מהירה של שרתי MCP.',
  },
  // Worktrees & Merge
  {
    id: 'panels-worktree-manage',
    section: 'panels',
    name: 'Open / + New session / Open folder / Refresh',
    tooltip: 'Focus tab / Start session here / Open folder / Reload list',
    detailEn: 'Manage worktrees and their sessions.',
    detailHe: 'נהל את ה-worktrees והסשנים שלהם.',
  },
  {
    id: 'panels-worktree-resolve-abort',
    section: 'panels',
    name: 'Resolve / Abort',
    tooltip: 'Open conflict resolver / Abort merge & restore',
    detailEn: 'Handle a paused merge.',
    detailHe: 'טפל במיזוג מושהה.',
  },
  {
    id: 'panels-worktree-create-cancel',
    section: 'panels',
    name: 'Create / Cancel / Discard and remove',
    tooltip: 'Create worktree / Keep worktree / Force-remove',
    detailEn: 'Create or force-remove a worktree.',
    detailHe: 'צור או הסר-בכוח worktree.',
  },
  {
    id: 'panels-worktree-merge-strategy',
    section: 'panels',
    name: 'Strategy cards (Merge)',
    tooltip: 'Merge commit / Squash / Fast-forward',
    detailEn: 'Choose a merge strategy.',
    detailHe: 'בחר אסטרטגיית מיזוג.',
  },
  {
    id: 'panels-worktree-merge-wizard',
    section: 'panels',
    name: 'Merge / Undo / Discard / Abort / Open conflicts',
    tooltip: 'Run merge / Revert / Rewrite history / Abort / Open files',
    detailEn: 'Drive the merge wizard.',
    detailHe: 'הפעל את אשף המיזוג.',
  },
  {
    id: 'panels-worktree-merge-assistant',
    section: 'panels',
    name: 'Ask Claude to help resolve / Send (assistant)',
    tooltip: 'Start a Claude conflict-resolve session / Send message',
    detailEn: 'Use the AI merge assistant.',
    detailHe: 'השתמש בעוזר המיזוג ב-AI.',
  },
  // Workstream Map
  {
    id: 'panels-workstream-back',
    section: 'panels',
    name: 'Back / All Projects',
    tooltip: 'Go back one level / View portfolio',
    detailEn: 'Navigate the map hierarchy.',
    detailHe: 'נווט בהיררכיית המפה.',
  },
  {
    id: 'panels-workstream-layers',
    section: 'panels',
    name: 'Current State / Plan Overlay / Resolve / Inactive / Low Confidence',
    tooltip: 'Toggle <layer/filter>',
    detailEn: 'Toggle map overlays and filters.',
    detailHe: 'החלף שכבות ומסננים במפה.',
  },
  {
    id: 'panels-workstream-build',
    section: 'panels',
    name: 'Import Folder / Reclassify / Build / Retry',
    tooltip: 'Import external folder / Rebuild map / Build / Retry',
    detailEn: 'Build or refresh the map.',
    detailHe: 'בנה או רענן את המפה.',
  },
  {
    id: 'panels-workstream-apply-nl',
    section: 'panels',
    name: 'Apply (NL command)',
    tooltip: 'Apply natural-language edit to map',
    detailEn: 'Run a natural-language map edit.',
    detailHe: 'הפעל עריכת מפה בשפה טבעית.',
  },
  {
    id: 'panels-workstream-resolve-toolbar',
    section: 'panels',
    name: 'Rename / Mark Complete / Mark Abandoned / Pin / Hide (Resolve toolbar)',
    tooltip: 'Rename / Complete / Abandon / Pin / Hide station',
    detailEn: 'Edit a workstream in resolve mode.',
    detailHe: 'ערוך זרם במצב resolve.',
  },
  {
    id: 'panels-workstream-reclassify-dismiss',
    section: 'panels',
    name: 'Re-Classify / Dismiss / Open project',
    tooltip: 'Rebuild map / Dismiss highlights / Open project',
    detailEn: 'Confidence review & resume actions.',
    detailHe: 'פעולות סקירת-ביטחון וחזרה.',
  },
  // Agent Teams
  {
    id: 'panels-teams-tabs',
    section: 'panels',
    name: 'Tabs (Topology/Tasks/Messages/Activity)',
    tooltip: 'View team <tab>',
    detailEn: 'Navigate team panel tabs.',
    detailHe: 'נווט בתאבי פאנל הצוות.',
  },
  {
    id: 'panels-teams-minimize',
    section: 'panels',
    name: 'Minimize (status widget)',
    tooltip: 'Minimize widget',
    detailEn: 'Collapse the floating team widget.',
    detailHe: "כווץ את ווידג'ט הצוות הצף.",
  },
  {
    id: 'panels-teams-add-task',
    section: 'panels',
    name: '+ Add Task / Add / Cancel',
    tooltip: 'Show form / Create task / Cancel',
    detailEn: 'Add a team task.',
    detailHe: 'הוסף משימת צוות.',
  },
  {
    id: 'panels-teams-send',
    section: 'panels',
    name: 'Send (Messages)',
    tooltip: 'Send message to agent',
    detailEn: 'Message a team agent.',
    detailHe: 'שלח הודעה לסוכן בצוות.',
  },
  {
    id: 'panels-teams-shutdown',
    section: 'panels',
    name: 'Shutdown (Activity)',
    tooltip: 'Shut down this agent',
    detailEn: 'Stop a team agent.',
    detailHe: 'עצור סוכן בצוות.',
  },
  // Multi-Participant
  {
    id: 'panels-mp-join-dialog',
    section: 'panels',
    name: 'Mode Join/Create, Provider Claude/Codex (Join dialog)',
    tooltip: 'Join / Create session, Use <provider>',
    detailEn: 'Configure the join/create dialog.',
    detailHe: 'הגדר את דיאלוג ההצטרפות/יצירה.',
  },
  {
    id: 'panels-mp-join-actions',
    section: 'panels',
    name: 'Cancel / Submit (Join)',
    tooltip: 'Close dialog / Create or join',
    detailEn: 'Close or submit the dialog.',
    detailHe: 'סגור או שלח את הדיאלוג.',
  },
  {
    id: 'panels-mp-send',
    section: 'panels',
    name: 'Send (MP input)',
    tooltip: 'Send message',
    detailEn: 'Send a message in the shared room.',
    detailHe: 'שלח הודעה בחדר המשותף.',
  },
  {
    id: 'panels-mp-emoji',
    section: 'panels',
    name: 'Emoji reactions (message)',
    tooltip: 'React with <emoji>',
    detailEn: 'Add an emoji reaction.',
    detailHe: "הוסף תגובת אימוג'י.",
  },
  {
    id: 'panels-mp-approval-guard',
    section: 'panels',
    name: 'Deny / Allow N / Always Allow / Force (Approval & Guard)',
    tooltip: 'Deny / Allow a budget / Always allow pair / Force (unsafe)',
    detailEn: 'Handle agent-to-agent approval requests.',
    detailHe: 'טפל בבקשות אישור בין-סוכנים.',
  },
  // SkillGen, Achievements, Review Loop, Accelerators, Settings, Bug Report
  {
    id: 'panels-skillgen-controls',
    section: 'panels',
    name: 'Open guide / Cancel (SkillGen)',
    tooltip: 'Open visual guide / Cancel generation',
    detailEn: 'Skill generation controls.',
    detailHe: 'בקרות יצירת Skills.',
  },
  {
    id: 'panels-skillgen-onboarding',
    section: 'panels',
    name: 'Language / Enable / Skip (SkillGen onboarding)',
    tooltip: 'Show in <lang> / Enable SkillDocs / Skip',
    detailEn: 'First-run SkillDocs choices.',
    detailHe: 'בחירות הפעלה ראשונה של SkillDocs.',
  },
  {
    id: 'panels-achievements-controls',
    section: 'panels',
    name: 'Got it / Turn off (Achievements)',
    tooltip: 'Close info / Turn off achievements',
    detailEn: 'Achievements info controls.',
    detailHe: 'בקרות מידע הישגים.',
  },
  {
    id: 'panels-community-actions',
    section: 'panels',
    name: 'Connect GitHub / Friends / Compare / Add friend / Publish (Community)',
    tooltip: 'Connect account / tabs / add friend / publish profile',
    detailEn: 'Community/social actions.',
    detailHe: 'פעולות קהילה/חברתי.',
  },
  {
    id: 'panels-pa-trace-show-more',
    section: 'panels',
    name: 'Show more/less (PA trace)',
    tooltip: 'Show all / fewer traces',
    detailEn: 'Expand the trace list.',
    detailHe: 'הרחב את רשימת ה-traces.',
  },
  {
    id: 'panels-pa-settings',
    section: 'panels',
    name: 'Enable/Disable / hooks / Clear Data / Refresh (PA settings)',
    tooltip: 'Toggle feature / install hook / clear data / refresh',
    detailEn: 'Particle Accelerator settings.',
    detailHe: 'הגדרות Particle Accelerator.',
  },
  {
    id: 'panels-super-pa-controls',
    section: 'panels',
    name: 'Enable / Disable / Close (Super-PA)',
    tooltip: 'Enable / Disable protection / Close',
    detailEn: 'Super Particle Accelerator controls.',
    detailHe: 'בקרות Super Particle Accelerator.',
  },
  {
    id: 'panels-settings-nav',
    section: 'panels',
    name: 'Close / tabs (Settings)',
    tooltip: 'Close panel / Show <tab> tab',
    detailEn: 'Settings panel navigation.',
    detailHe: 'ניווט בפאנל ההגדרות.',
  },
  {
    id: 'panels-bug-report-controls',
    section: 'panels',
    name: 'Quick/AI tabs, Send, Preview, Submit, Approve/Reject script (Bug Report)',
    tooltip: 'Switch mode / send / preview / submit / run-or-reject script',
    detailEn: 'Bug-report flow controls.',
    detailHe: 'בקרות זרימת דיווח הבאג.',
  },
  // Vitals info & misc widgets
  {
    id: 'panels-vitals-feature-toggles',
    section: 'panels',
    name: 'Feature toggles (Vitals info)',
    tooltip: 'Toggle <feature>',
    detailEn: 'Enable/disable Adventure, Weather, semantic analysis, SkillGen, Usage widget, session restore, Vitals, activity summary.',
    detailHe: 'הפעל/כבה את הפיצ\'רים השונים.',
  },
  {
    id: 'panels-copy-image',
    section: 'panels',
    name: 'Copy image (Image Lightbox menu)',
    tooltip: 'Copy image with annotations to clipboard',
    detailEn: 'Copy an annotated image.',
    detailHe: 'העתק תמונה עם הערות.',
  },
  {
    id: 'panels-audit-log-refresh',
    section: 'panels',
    name: 'Refresh (Audit Log)',
    tooltip: 'Reload audit events and report',
    detailEn: 'Refresh the audit log.',
    detailHe: 'רענן את יומן הביקורת.',
  },
  {
    id: 'panels-smart-search-send',
    section: 'panels',
    name: 'Send (Smart Search)',
    tooltip: 'Send search query (Ctrl+Enter)',
    detailEn: 'Submit a Smart Search query.',
    detailHe: 'שלח שאילתת Smart Search.',
  },
  {
    id: 'panels-smart-search-example',
    section: 'panels',
    name: 'Example query (empty state)',
    tooltip: 'Use example: <query>',
    detailEn: 'Fill the input with an example.',
    detailHe: 'מלא את הקלט בדוגמה.',
  },
  {
    id: 'panels-file-mention-item',
    section: 'panels',
    name: 'File mention item',
    tooltip: 'Mention <path>',
    detailEn: 'Insert an @file mention.',
    detailHe: 'הכנס אזכור @file.',
  },

  // ===== Part 6 — Selectors =====
  {
    id: 'selectors-model-provider-permission',
    section: 'selectors',
    name: 'Model / Provider / Permission Mode / effort & service-tier',
    detailEn: 'Model, Provider, Permission Mode, and the Codex/Claude effort & service-tier selectors are native <select> dropdowns. Each carries a data-tooltip on the <select> element describing what it controls, so hovering the control shows the tooltip; the individual options are native and self-labeled.',
    detailHe: 'בוררי Model, Provider, Permission Mode, ו-effort/service-tier של Codex/Claude הם תפריטי <select> מקוריים. כל אחד נושא data-tooltip על אלמנט ה-<select> המתאר מה הוא שולט בו, כך שריחוף מעל הפקד מציג את ה-tooltip; ה-option עצמם מקוריים וברורים.',
  },
];
