/**
 * Workstream Map data model.
 * Defines all types for the subway-map style project visualization.
 */

// --- Core enums ---

export type WorkstreamType =
  | 'feature'
  | 'bug_fix'
  | 'research'
  | 'refactor'
  | 'infrastructure'
  | 'experiment'
  | 'abandoned_experiment'
  | 'uncategorized';

export type WorkstreamStatus =
  | 'active'
  | 'completed'
  | 'blocked'
  | 'uncertain'
  | 'research'
  | 'abandoned'
  | 'planning';

export type StationType =
  | 'session'
  | 'decision'
  | 'code_change'
  | 'problem'
  | 'milestone'
  | 'failure'
  | 'uncertainty'
  | 'blocker'
  | 'direction_change'
  | 'merge_point'
  | 'split_point'
  | 'plan_step';

export type StationStatus =
  | 'completed'
  | 'partial'
  | 'failed'
  | 'pending'
  | 'skipped';

export type LineTexture =
  | 'solid'
  | 'dashed'
  | 'blurred'
  | 'broken';

export type ModelTier =
  | 'sonnet'
  | 'haiku'
  | 'local_heuristic';

export type WorkstreamSource =
  | 'session'
  | 'external_folder';

// --- Supporting types ---

export interface WorkstreamBlocker {
  id: string;
  label: string;
  description: string;
  severity: 'low' | 'medium' | 'high';
  stationId?: string;
  sessionId?: string;
  createdAt: string;
  resolvedAt?: string;
}

export interface PendingDecision {
  id: string;
  label: string;
  options?: string[];
  stationId?: string;
  sessionId?: string;
  createdAt: string;
}

export interface ModelRunLogEntry {
  id: string;
  modelTier: ModelTier;
  task:
    | 'workstream_classification'
    | 'station_extraction'
    | 'current_state_synthesis'
    | 'plan_reality_comparison'
    | 'semantic_edit'
    | 'resume_diff';
  startedAt: string;
  completedAt?: string;
  inputHash: string;
  outputHash?: string;
  costUsd?: number;
  error?: string;
}

// --- Workstream current state ---

export interface WorkstreamCurrentState {
  phase:
    | 'not_started'
    | 'planning'
    | 'implementation'
    | 'debugging'
    | 'testing'
    | 'review'
    | 'blocked'
    | 'complete'
    | 'abandoned'
    | 'unknown';

  summary: string;
  lastMeaningfulProgress: string;
  nextLikelyAction: string;
  openQuestions: string[];
  blockers: WorkstreamBlocker[];
  pendingDecisions: PendingDecision[];
  evidenceSessionIds: string[];
  evidenceStationIds: string[];
  generatedBy: ModelTier;
  generatedAt: string;
}

// --- Metrics and visual state ---

export interface WorkstreamMetrics {
  totalSessions: number;
  totalTurns: number;
  totalCostUsd: number;
  filesModified: string[];
  filesRead: string[];
  failureCount: number;
  blockerCount: number;
  decisionCount: number;
}

export interface WorkstreamVisualState {
  colorToken: string;
  texture: LineTexture;
  thickness: number;
  opacity: number;
  collapsed: boolean;
  highlighted: boolean;
  needsAttention: boolean;
  resumeRecommended: boolean;
}

// --- Workstream ---

export interface Workstream {
  id: string;
  projectId: string;

  label: string;
  goal: string;
  type: WorkstreamType;
  status: WorkstreamStatus;

  sessionIds: string[];
  source?: WorkstreamSource;
  sourceFolderPath?: string;
  sourceFilePaths?: string[];
  sourceImportedAt?: string;
  sourceDocumentCount?: number;
  sourceTotalBytes?: number;
  relatedWorkstreamIds: string[];
  parentWorkstreamId?: string;
  childWorkstreamIds: string[];
  mergedIntoWorkstreamId?: string;

  confidence: number;
  confidenceReasons: string[];
  autoGenerated: boolean;
  userPinned: boolean;

  importanceScore: number;
  attentionScore: number;

  currentState: WorkstreamCurrentState;

  startedAt: string;
  lastActivityAt: string;
  completedAt?: string;
  lastViewedAt?: string;

  planId?: string;
  planReality?: PlanReality;

  metrics: WorkstreamMetrics;

  visual: WorkstreamVisualState;

  order: number;
}

// --- Station ---

export interface StationEvidence {
  kind: 'session_summary' | 'tool_use' | 'file_change' | 'test_result' | 'user_message' | 'assistant_message' | 'external_document';
  sessionId?: string;
  turnIndex?: number;
  text?: string;
  filePath?: string;
}

export interface StationVisualState {
  size: 'small' | 'medium' | 'large';
  glow: 'none' | 'recent' | 'attention' | 'resolved' | 'uncertain';
  labelVisible: boolean;
}

export interface Station {
  id: string;
  projectId: string;
  workstreamId: string;

  type: StationType;
  status: StationStatus;

  label: string;
  description: string;
  whyItMatters: string;

  sessionId?: string;
  turnIndex?: number;
  sourceFilePaths?: string[];

  order: number;
  timestamp: string;

  importanceScore: number;
  attentionScore: number;
  visibleInProjectMap: boolean;

  splitToWorkstreamIds?: string[];
  mergedFromWorkstreamIds?: string[];

  confidence: number;
  evidence: StationEvidence[];

  visual: StationVisualState;
}

// --- Plan reality model ---

export interface PlanSource {
  kind: 'session' | 'markdown_file' | 'html_plan' | 'user_created';
  sessionId?: string;
  filePath?: string;
}

export interface PlanStep {
  id: string;
  label: string;
  description?: string;
  order: number;
  status: StationStatus;
  linkedStationIds: string[];
  deviationNote?: string;
  confidence: number;
}

export interface PlanReality {
  planId: string;
  planLabel: string;
  planSource: PlanSource;
  steps: PlanStep[];
  overallStatus: 'on_track' | 'deviated' | 'blocked' | 'completed' | 'unknown';
  deviationSummary: string;
  lastComparedAt: string;
  generatedBy: ModelTier;
}

// --- Split and merge ---

export interface Split {
  id: string;
  projectId: string;
  fromWorkstreamId: string;
  toWorkstreamIds: string[];
  stationId: string;
  reason: string;
  confidence: number;
  timestamp: string;
}

export interface Merge {
  id: string;
  projectId: string;
  fromWorkstreamIds: string[];
  toWorkstreamId: string;
  stationId: string;
  reason: string;
  confidence: number;
  timestamp: string;
}

// --- User edits ---

export interface UserEdit {
  id: string;
  projectId: string;
  type:
    | 'move_session'
    | 'merge_workstreams'
    | 'split_workstream'
    | 'rename_workstream'
    | 'reclassify_workstream'
    | 'hide_station'
    | 'add_milestone'
    | 'mark_complete'
    | 'mark_abandoned'
    | 'change_status'
    | 'pin_workstream'
    | 'unpin_workstream';

  timestamp: string;
  actor: 'user' | 'ai_assisted_user';
  details: Record<string, unknown>;
  protectedFromAiOverwrite: boolean;
}

// --- Project map state ---

export interface ProjectCurrentState {
  summary: string;
  activeWorkstreamIds: string[];
  blockedWorkstreamIds: string[];
  completedWorkstreamIds: string[];
  uncertainWorkstreamIds: string[];
  recommendedResumeWorkstreamId?: string;
  recommendedResumeStationId?: string;
  recommendedNextAction?: string;
  openQuestions: string[];
  blockers: WorkstreamBlocker[];
  generatedAt: string;
  generatedBy: ModelTier;
}

export interface ResumeState {
  since: string;
  newWorkstreamIds: string[];
  changedWorkstreamIds: string[];
  newStationIds: string[];
  resolvedBlockerIds: string[];
  newBlockerIds: string[];
  newlyCompletedWorkstreamIds: string[];
  summary: string;
  recommendedResumeWorkstreamId?: string;
}

export interface ProjectMapState {
  projectId: string;
  projectLabel: string;
  workspacePath: string;

  workstreams: Workstream[];
  stations: Station[];
  splits: Split[];
  merges: Merge[];

  currentState: ProjectCurrentState;
  resumeState?: ResumeState;

  lastClassifiedAt: string;
  lastOpenedAt?: string;
  lastViewedSnapshotId?: string;

  userEdits: UserEdit[];
  archivedWorkstreamIds: string[];

  modelRunLog: ModelRunLogEntry[];

  schemaVersion: number;
}

// --- Snapshot for Resume View ---

export interface WorkstreamMapSnapshot {
  id: string;
  projectId: string;
  createdAt: string;
  workstreamHashes: Record<string, string>;
  stationHashes: Record<string, string>;
  currentStateHash: string;
}

// --- Classification pipeline types ---

export interface CandidateCluster {
  id: string;
  sessionIds: string[];
  labelHint?: string;
  reasons: string[];
  confidence: number;
}

export interface ClassificationOutput {
  workstreams: Array<{
    id?: string;
    label: string;
    goal: string;
    type: WorkstreamType;
    status: WorkstreamStatus;
    sessionIds: string[];
    confidence: number;
    confidenceReasons: string[];
    importanceScore: number;
    currentState: Partial<WorkstreamCurrentState>;
  }>;
  splits: Array<{
    fromSessionId: string;
    reason: string;
    childLabels: string[];
    confidence: number;
  }>;
  merges: Array<{
    workstreamLabels: string[];
    reason: string;
    confidence: number;
  }>;
  projectCurrentState: Partial<ProjectCurrentState>;
}

export interface StationExtractionOutput {
  stations: Array<{
    type: StationType;
    label: string;
    description: string;
    whyItMatters: string;
    status: StationStatus;
    importanceScore: number;
    attentionScore: number;
    evidence: StationEvidence[];
    confidence: number;
  }>;
}

// --- NL edit types ---

export interface NLEditResult {
  edits: UserEdit[];
  explanation: string;
  requiresConfirmation: boolean;
  confidence: number;
}

export interface MapInteractionContext {
  focusedWorkstreamId?: string;
  selectedStationId?: string;
  hoveredEntityId?: string;
  visibleWorkstreamIds: string[];
}

// --- Classification options ---

export interface ClassificationOptions {
  force?: boolean;
  incrementalSessionIds?: string[];
}

// --- Layout types ---

export interface SvgPathDefinition {
  d: string;
  color: string;
  texture: LineTexture;
  thickness: number;
  opacity: number;
}

export interface MapLayout {
  workstreamPaths: Record<string, SvgPathDefinition>;
  stationPositions: Record<string, { x: number; y: number }>;
  labelPositions: Record<string, { x: number; y: number }>;
  junctionPositions: Record<string, { x: number; y: number }>;
  bounds: { width: number; height: number };
}

// --- Filter types ---

export interface WorkstreamMapFilter {
  statuses: WorkstreamStatus[];
  types: WorkstreamType[];
  showInactive: boolean;
  showLowConfidence: boolean;
  showLowImportanceStations: boolean;
  changedSince?: string;
  textQuery?: string;
}

// --- Session enrichment (extends existing SessionSummary) ---

export interface EnrichedSessionData {
  sessionId: string;
  firstPrompt?: string;
  summary?: string;
  filesModified?: string[];
  filesRead?: string[];
  gitBranch?: string;
  gitCommit?: string;
  taskType?: string;
  outcome?: 'completed' | 'failed' | 'partial' | 'unknown';
  startedAt?: string;
  endedAt?: string;
  totalTurns?: number;
  totalCostUsd?: number;
}

// --- Workstream visual color palette ---

export const WORKSTREAM_STATUS_COLORS: Record<WorkstreamStatus, string> = {
  active: '#4A9EFF',
  completed: '#4ADE80',
  blocked: '#F87171',
  uncertain: '#FACC15',
  research: '#A78BFA',
  abandoned: '#9CA3AF',
  planning: '#7DD3FC',
};

export const STATION_TYPE_SHAPES: Record<StationType, string> = {
  session: 'circle',
  decision: 'diamond',
  code_change: 'square',
  problem: 'triangle',
  milestone: 'star',
  failure: 'x',
  uncertainty: 'question',
  blocker: 'lock',
  direction_change: 'curved-arrow',
  merge_point: 'junction',
  split_point: 'junction',
  plan_step: 'outlined-circle',
};

// --- User Portfolio (cross-project) ---

export type ProjectHealth = 'healthy' | 'needs_attention' | 'blocked' | 'stale';

export interface ProjectWorkstreamSummary {
  id: string;
  label: string;
  status: WorkstreamStatus;
  confidence: number;
  lastActivityAt: string;
  phase: string;
  colorToken: string;
  stationCount: number;
}

export interface ProjectSummaryEntry {
  projectId: string;
  projectPath: string;
  projectName: string;

  lastActivityAt: string;
  lastClassifiedAt: string;
  lastOpenedAt: string;

  activeWorkstreams: number;
  blockedWorkstreams: number;
  completedWorkstreams: number;
  uncertainWorkstreams: number;
  totalWorkstreams: number;

  topWorkstreams: ProjectWorkstreamSummary[];

  overallHealth: ProjectHealth;
  healthReasons: string[];

  totalSessions: number;
  recentSessions: number;

  currentStateSummary: string;
  recommendedNextAction: string;
  openBlockerCount: number;

  cachedMapState?: ProjectMapState;
  pathExists?: boolean;
}

export interface CrossProjectResumeRecommendation {
  projectId: string;
  projectName: string;
  workstreamId: string;
  workstreamLabel: string;
  reason: string;
  confidence: number;
}

export interface UserPortfolioState {
  projects: ProjectSummaryEntry[];
  crossProjectResume: CrossProjectResumeRecommendation | null;
  lastUpdatedAt: string;
}

export const CURRENT_SCHEMA_VERSION = 1;
